In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")
sns.set_context("notebook")
sns.set_context("poster")

# Data Preprocessing

Most of Machine Learning algorithms make assumptions on your data, for example that the scales are comparable or simply they work only on numerical data. This implies that we need to pre-process the data. 
User oriented applications, such as BigML, do that automatically. However, when you use a language such as Python or R, you have to do it manually and decide for each attribute. 

In the Machine Learning process (see figure below) pre-processing is the first step after loading and examining your data. 

There are 4 basic processes that we will treat separatelty. Depending on the algorithm that we will use, we'll need to apply all of them or only some:

        1) Rescale data.
        2) Standarize data.
        3) Normalize data. 
        4) Binarize data. 
        
Before the pre-processing there are three(3) important steps:

        a) Load your dataset
        b) Examine it and get rid of everything that doesn't apply.
        c) Split the dataset into the input and output variables.
        
You will observe that scikit-learn provides two equivalent ways. First you can use the fit() function to prepare your data and later the transform() function. Or you can use the combined fit-and-transform.

![text](ML_process.png)

<img src="Pima_indians_cowboy_1889.jpg">

In this exercise we will use one of the traditional Machine Learning dataset, the Pima Indians diabetes dataset.

This dataset is originally from the National Institute of Diabetes and Digestive and Kidney Diseases. The objective of the dataset is to diagnostically predict whether or not a patient has diabetes, based on certain diagnostic measurements included in the dataset. Several constraints were placed on the selection of these instances from a larger database. In particular, all patients here are females at least 21 years old of Pima Indian heritage.

Content
The datasets consists of several medical predictor variables and one target variable, <b>Outcome</b>. Predictor variables includes the number of pregnancies the patient has had, their BMI, insulin level, age, and so on.
<blockquote>
        <ul style="list-style-type:square;">
            <li>Pregnancies</li> 
            <li>Glucose</li>
            <li>BloodPressure</li>
            <li>SkinThickness</li>
            <li>Insulin</li>
            <li>BMI</li>
            <li>DiabetesPedigreeFunction</li>
            <li>Age</li>
            <li>Outcome</li>
        </ul>
</blockquote>

In [4]:
# Load the Pima indians dataset and separate input and output components 

from numpy import set_printoptions
set_printoptions(precision=3)

filename="pima-indians-diabetes.data.csv"
names=["pregnancies", "glucose", "pressure", "skin", "insulin", "bmi", "pedi", "age", "outcome"]
p_indians=pd.read_csv(filename, names=names)
p_indians.head()

# First we separate into input and output components
array = p_indians.values
X = array[:,0:8]
Y = array[:,8]
X
pd.DataFrame(X).head()

   pregnancies  glucose  pressure  skin  insulin   bmi   pedi  age  outcome
0            6      148        72    35        0  33.6  0.627   50        1
1            1       85        66    29        0  26.6  0.351   31        0
2            8      183        64     0        0  23.3  0.672   32        1
3            1       89        66    23       94  28.1  0.167   21        0
4            0      137        40    35      168  43.1  2.288   33        1

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

     0      1     2     3      4     5      6     7
0  6.0  148.0  72.0  35.0    0.0  33.6  0.627  50.0
1  1.0   85.0  66.0  29.0    0.0  26.6  0.351  31.0
2  8.0  183.0  64.0   0.0    0.0  23.3  0.672  32.0
3  1.0   89.0  66.0  23.0   94.0  28.1  0.167  21.0
4  0.0  137.0  40.0  35.0  168.0  43.1  2.288  33.0

<h1> Rescale Data </h1>

It is very common that the attributes have very different scales. Therefore, many machine learning algorithms benefit from rescalling the attributes to all have the same scale. Normally between 0 and 1. This process is commonly called normalization. 

This is important with optimization algorithms that use gradient descent. Also with algorithms, like regressions, that weight inputs like regression or neural networks. It is also needed when the the algorithms use distances such as the case of k-means or k-nn(K-Nearest Neighbors). 

For rescaling your data, you use the <b> MinMaxScaler </b> class.

In [5]:
# Rescale data between 0 and 1

p_indians.head()

from sklearn.preprocessing import MinMaxScaler

# Scale between 0 and 1

scaler = MinMaxScaler(feature_range = (0,1))
rescaledX = scaler.fit_transform(X)

rescaledX

   pregnancies  glucose  pressure  skin  insulin   bmi   pedi  age  outcome
0            6      148        72    35        0  33.6  0.627   50        1
1            1       85        66    29        0  26.6  0.351   31        0
2            8      183        64     0        0  23.3  0.672   32        1
3            1       89        66    23       94  28.1  0.167   21        0
4            0      137        40    35      168  43.1  2.288   33        1

array([[0.353, 0.744, 0.59 , ..., 0.501, 0.234, 0.483],
       [0.059, 0.427, 0.541, ..., 0.396, 0.117, 0.167],
       [0.471, 0.92 , 0.525, ..., 0.347, 0.254, 0.183],
       ...,
       [0.294, 0.608, 0.59 , ..., 0.39 , 0.071, 0.15 ],
       [0.059, 0.633, 0.492, ..., 0.449, 0.116, 0.433],
       [0.059, 0.467, 0.574, ..., 0.453, 0.101, 0.033]])

<h1>Standarize Data </h1>

Standarization is a technique that assumes a Gaussians distribution but different means and standard deviations.
Transforming them to a Gaussian of mean 0 and standard deviation of 1. 

It is most suitable for techniques that assume a Gaussian distribution in the input variables and work better with 
rescaled data, such as linear regression, logistic regression or LDA (linear discriminant analysis).

For standarizing you use the <b>StandardScaler</b> class.

In [6]:
# Standardize data (0 mean, 1 stdev)

from sklearn.preprocessing import StandardScaler

p_indians.head()

scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)

rescaledX

   pregnancies  glucose  pressure  skin  insulin   bmi   pedi  age  outcome
0            6      148        72    35        0  33.6  0.627   50        1
1            1       85        66    29        0  26.6  0.351   31        0
2            8      183        64     0        0  23.3  0.672   32        1
3            1       89        66    23       94  28.1  0.167   21        0
4            0      137        40    35      168  43.1  2.288   33        1

array([[ 0.64 ,  0.848,  0.15 , ...,  0.204,  0.468,  1.426],
       [-0.845, -1.123, -0.161, ..., -0.684, -0.365, -0.191],
       [ 1.234,  1.944, -0.264, ..., -1.103,  0.604, -0.106],
       ...,
       [ 0.343,  0.003,  0.15 , ..., -0.735, -0.685, -0.276],
       [-0.845,  0.16 , -0.471, ..., -0.24 , -0.371,  1.171],
       [-0.845, -0.873,  0.046, ..., -0.202, -0.474, -0.871]])

<b><font color="red" size=6>Mission 1</font>

a) Sometimes we only want to standarize some attributes and not all. 
For the shake of example, let's say that we only want standarize glucose.
<br><br>
b) Create a new X with all the attributes of the all X but the standarized glucose.
<br><br>
c) Do the same Scaling (from 0 to 1) instead of Standarizing. 
<br><br>
hint: we are dealing with numpy arrays and not DataFrames here, you should use np.concatenate()
</b>

In [12]:
# a) Sometimes we only want to standarize some attributes and not all. For the shake of example, let's say that we only want standarize glucose.

gluc = p_indians[["glucose"]]
stand_gluc = StandardScaler().fit(gluc).transform(gluc)
stand_gluc

array([[ 8.483e-01],
       [-1.123e+00],
       [ 1.944e+00],
       [-9.982e-01],
       [ 5.041e-01],
       [-1.532e-01],
       [-1.342e+00],
       [-1.845e-01],
       [ 2.382e+00],
       [ 1.285e-01],
       [-3.410e-01],
       [ 1.474e+00],
       [ 5.666e-01],
       [ 2.132e+00],
       [ 1.412e+00],
       [-6.539e-01],
       [-9.059e-02],
       [-4.349e-01],
       [-5.600e-01],
       [-1.845e-01],
       [ 1.598e-01],
       [-6.852e-01],
       [ 2.351e+00],
       [-5.929e-02],
       [ 6.918e-01],
       [ 1.285e-01],
       [ 8.170e-01],
       [-7.478e-01],
       [ 7.544e-01],
       [-1.219e-01],
       [-3.723e-01],
       [ 1.161e+00],
       [-1.030e+00],
       [-9.043e-01],
       [ 3.460e-02],
       [-5.600e-01],
       [ 5.354e-01],
       [-5.913e-01],
       [-9.669e-01],
       [-3.097e-01],
       [ 1.850e+00],
       [ 3.789e-01],
       [-4.662e-01],
       [ 1.568e+00],
       [ 1.193e+00],
       [ 1.850e+00],
       [ 7.857e-01],
       [-1.562e+00],
       [-5.600e-01],
       [-4.975e-01],
       [-5.600e-01],
       [-6.226e-01],
       [-1.030e+00],
       [ 1.725e+00],
       [ 9.109e-01],
       [-1.499e+00],
       [ 2.069e+00],
       [-6.539e-01],
       [ 7.857e-01],
       [-4.975e-01],
       [-1.155e+00],
       [ 3.789e-01],
       [-2.407e+00],
       [ 6.292e-01],
       [-2.158e-01],
       [-6.852e-01],
       [-3.723e-01],
       [-3.723e-01],
       [-8.104e-01],
       [ 7.857e-01],
       [-6.539e-01],
       [ 5.666e-01],
       [ 1.598e-01],
       [ 2.537e-01],
       [-1.311e+00],
       [-3.784e+00],
       [-1.843e+00],
       [-8.104e-01],
       [ 3.163e-01],
       [-2.784e-01],
       [-2.471e-01],
       [-1.468e+00],
       [-1.186e+00],
       [-6.226e-01],
       [ 5.041e-01],
       [-3.410e-01],
       [-4.662e-01],
       [-6.539e-01],
       [ 4.728e-01],
       [-4.349e-01],
       [-1.280e+00],
       [ 6.590e-02],
       [-1.249e+00],
       [ 4.102e-01],
       [ 6.605e-01],
       [ 7.231e-01],
       [-9.043e-01],
       [-1.562e+00],
       [-8.730e-01],
       [ 3.460e-02],
       [ 1.318e+00],
       [ 9.422e-01],
       [ 1.285e-01],
       [-1.249e+00],
       [-1.123e+00],
       [ 1.598e-01],
       [-7.791e-01],
       [ 7.231e-01],
       [-1.186e+00],
       [-8.104e-01],
       [ 1.568e+00],
       [ 1.067e+00],
       [-9.982e-01],
       [-1.405e+00],
       [ 1.224e+00],
       [ 7.857e-01],
       [ 9.719e-02],
       [-1.342e+00],
       [-7.478e-01],
       [-6.852e-01],
       [ 1.286e+00],
       [-3.097e-01],
       [-4.349e-01],
       [ 3.476e-01],
       [-2.471e-01],
       [-1.030e+00],
       [-2.800e-02],
       [-9.059e-02],
       [-1.219e-01],
       [-4.975e-01],
       [ 1.631e+00],
       [ 3.460e-02],
       [ 1.537e+00],
       [-1.155e+00],
       [-7.791e-01],
       [ 1.285e-01],
       [-6.539e-01],
       [-8.730e-01],
       [ 2.537e-01],
       [-4.975e-01],
       [ 2.224e-01],
       [-4.662e-01],
       [-4.036e-01],
       [-4.036e-01],
       [ 1.036e+00],
       [-5.913e-01],
       [-2.000e+00],
       [-4.662e-01],
       [ 8.170e-01],
       [-9.669e-01],
       [ 4.728e-01],
       [-2.158e-01],
       [ 1.099e+00],
       [ 1.005e+00],
       [ 2.100e+00],
       [ 9.735e-01],
       [-6.852e-01],
       [-3.723e-01],
       [-1.030e+00],
       [ 1.318e+00],
       [ 9.422e-01],
       [-5.913e-01],
       [-2.158e-01],
       [-6.539e-01],
       [ 3.163e-01],
       [-5.288e-01],
       [ 8.483e-01],
       [-2.800e-02],
       [-3.410e-01],
       [-3.097e-01],
       [-5.913e-01],
       [ 4.102e-01],
       [-1.061e+00],
       [-1.311e+00],
       [-1.436e+00],
       [ 1.819e+00],
       [-1.123e+00],
       [ 2.537e-01],
       [ 6.918e-01],
       [ 2.850e-01],
       [-1.061e+00],
       [-5.929e-02],
       [-3.784e+00],
       [-1.499e+00],
       [ 6.292e-01],
       [ 2.288e+00],
       [ 1.881e+00],
       [ 2.224e-01],
       [-3.723e-01],
       [ 5.666e-01],
       [-3.097e-01],
       [ 6.590e-02],
       [ 1.193e+00],
       [ 4.415e-01],
       [-1.123e+00],
       [ 1.161e+00],
       [-4.975e-01],
       [-4.349e-01],
       [-3.723e-01],
       [ 8.483e-01],
       [-2.471e-01],
       [ 5.354e-01],
       [-4.036e-01],
       [-6.852e-01],
       [-5.600e-01],
       [-3.097e-01],
       [ 2.351e+00],
       [ 1.286e+00],
       [-7.791e-01],
       [ 1.975e+00],
       [-1.249e+00],
       [ 8.170e-01],
       [ 1.819e+00],
       [ 5.979e-01],
       [-2.784e-01],
       [ 9.422e-01],
       [-3.723e-01],
       [ 1.285e-01],
       [-1.123e+00],
       [-2.784e-01],
       [ 1.756e+00],
       [ 1.161e+00],
       [-5.929e-02],
       [ 6.605e-01],
       [-6.539e-01],
       [-1.061e+00],
       [-6.226e-01],
       [ 1.286e+00],
       [ 2.382e+00],
       [-1.219e-01],
       [ 6.605e-01],
       [ 4.102e-01],
       [-1.311e+00],
       [ 3.460e-02],
       [-1.468e+00],
       [ 1.568e+00],
       [ 1.881e+00],
       [ 1.819e+00],
       [ 1.349e+00],
       [-5.288e-01],
       [-9.356e-01],
       [-9.356e-01],
       [ 5.666e-01],
       [-5.929e-02],
       [ 7.857e-01],
       [ 1.975e+00],
       [ 3.460e-02],
       [ 1.380e+00],
       [ 9.719e-02],
       [-3.097e-01],
       [-4.662e-01],
       [ 2.537e-01],
       [-9.669e-01],
       [-1.092e+00],
       [-9.043e-01],
       [-2.471e-01],
       [-3.097e-01],
       [-2.158e-01],
       [ 2.257e+00],
       [ 1.067e+00],
       [ 2.194e+00],
       [ 6.292e-01],
       [-8.104e-01],
       [ 6.605e-01],
       [ 6.590e-02],
       [-7.791e-01],
       [ 5.354e-01],
       [ 2.224e-01],
       [-5.913e-01],
       [ 7.857e-01],
       [-6.226e-01],
       [-4.036e-01],
       [ 3.460e-02],
       [-1.562e+00],
       [-4.662e-01],
       [-6.539e-01],
       [-4.662e-01],
       [-5.288e-01],
       [-2.158e-01],
       [-4.036e-01],
       [ 7.857e-01],
       [ 2.537e-01],
       [ 3.789e-01],
       [ 1.255e+00],
       [-4.036e-01],
       [ 4.728e-01],
       [ 1.067e+00],
       [-5.929e-02],
       [-7.791e-01],
       [-4.036e-01],
       [-1.342e+00],
       [-4.349e-01],
       [ 2.224e-01],
       [ 2.224e-01],
       [ 1.255e+00],
       [ 9.422e-01],
       [ 7.857e-01],
       [ 1.598e-01],
       [-6.539e-01],
       [-2.784e-01],
       [ 1.443e+00],
       [ 7.231e-01],
       [-1.374e+00],
       [-1.845e-01],
       [ 9.109e-01],
       [-2.800e-02],
       [ 1.255e+00],
       [ 5.041e-01],
       [ 2.224e-01],
       [ 9.719e-02],
       [-1.280e+00],
       [-4.662e-01],
       [ 1.067e+00],
       [-2.471e-01],
       [-3.723e-01],
       [-2.784e-01],
       [-6.852e-01],
       [ 1.912e+00],
       [-1.845e-01],
       [ 2.288e+00],
       [ 2.537e-01],
       [-2.784e-01],
       [ 9.719e-02],
       [ 9.735e-01],
       [-2.784e-01],
       [ 1.130e+00],
       [ 3.460e-02],
       [ 1.819e+00],
       [-5.913e-01],
       [-4.975e-01],
       [-9.059e-02],
       [-1.061e+00],
       [ 1.850e+00],
       [-4.662e-01],
       [-8.104e-01],
       [ 1.380e+00],
       [-1.219e-01],
       [-1.845e-01],
       [ 9.735e-01],
       [ 1.787e+00],
       [ 2.850e-01],
       [-8.104e-01],
       [-3.784e+00],
       [ 3.460e-02],
       [-8.104e-01],
       [ 1.598e-01],
       [ 5.666e-01],
       [-1.532e-01],
       [-6.852e-01],
       [-3.784e+00],
       [-9.043e-01],
       [ 5.041e-01],
       [-1.875e+00],
       [-9.669e-01],
       [-9.669e-01],
       [ 1.380e+00],
       [ 1.285e-01],
       [ 2.537e-01],
       [-1.030e+00],
       [ 2.351e+00],
       [ 2.132e+00],
       [ 1.161e+00],
       [-5.600e-01],
       [ 7.857e-01],
       [ 8.170e-01],
       [-6.852e-01],
       [ 9.719e-02],
       [-6.226e-01],
       [-1.249e+00],
       [ 3.789e-01],
       [ 1.631e+00],
       [-9.059e-02],
       [-1.155e+00],
       [-4.975e-01],
       [ 3.460e-02],
       [ 5.979e-01],
       [-7.165e-01],
       [-1.061e+00],
       [ 1.099e+00],
       [-8.730e-01],
       [-4.349e-01],
       [-4.975e-01],
       [-3.723e-01],
       [-9.669e-01],
       [ 1.285e-01],
       [-5.929e-02],
       [-1.532e-01],
       [-4.975e-01],
       [ 7.231e-01],
       [-6.539e-01],
       [-6.539e-01],
       [ 1.412e+00],
       [ 3.163e-01],
       [-1.532e-01],
       [ 1.161e+00],
       [ 1.911e-01],
       [-7.791e-01],
       [ 3.163e-01],
       [-1.217e+00],
       [ 2.257e+00],
       [-8.104e-01],
       [ 5.041e-01],
       [ 4.728e-01],
       [-1.530e+00],
       [ 1.474e+00],
       [ 6.590e-02],
       [-1.845e-01],
       [-6.226e-01],
       [ 2.382e+00],
       [ 1.599e+00],
       [-5.913e-01],
       [-2.784e-01],
       [ 6.918e-01],
       [ 6.918e-01],
       [ 5.354e-01],
       [ 1.631e+00],
       [-7.478e-01],
       [ 7.231e-01],
       [-1.186e+00],
       [ 2.537e-01],
       [-5.929e-02],
       [-8.417e-01],
       [-5.913e-01],
       [-1.845e-01],
       [ 9.422e-01],
       [ 1.975e+00],
       [-8.417e-01],
       [ 1.881e+00],
       [ 4.415e-01],
       [-8.104e-01],
       [-6.852e-01],
       [-9.982e-01],
       [-1.280e+00],
       [ 5.666e-01],
       [-9.669e-01],
       [ 6.292e-01],
       [ 5.979e-01],
       [ 8.170e-01],
       [-7.478e-01],
       [-4.349e-01],
       [ 2.132e+00],
       [-1.186e+00],
       [-1.219e-01],
       [-4.036e-01],
       [-1.219e-01],
       [ 1.850e+00],
       [-6.539e-01],
       [-8.104e-01],
       [-5.288e-01],
       [-2.800e-02],
       [-1.217e+00],
       [ 4.102e-01],
       [-9.356e-01],
       [-5.929e-02],
       [-6.539e-01],
       [ 1.693e+00],
       [ 4.415e-01],
       [-1.092e+00],
       [ 8.483e-01],
       [ 4.102e-01],
       [-2.800e-02],
       [-1.562e+00],
       [-1.468e+00],
       [-1.030e+00],
       [-1.845e-01],
       [ 9.719e-02],
       [-1.468e+00],
       [-7.478e-01],
       [-2.800e-02],
       [ 1.036e+00],
       [ 7.231e-01],
       [ 5.041e-01],
       [-5.929e-02],
       [ 4.728e-01],
       [-2.158e-01],
       [ 5.041e-01],
       [-4.975e-01],
       [-2.158e-01],
       [ 1.598e-01],
       [ 3.476e-01],
       [ 1.161e+00],
       [ 6.590e-02],
       [-1.123e+00],
       [-1.155e+00],
       [ 7.544e-01],
       [ 4.415e-01],
       [ 5.666e-01],
       [ 1.631e+00],
       [-6.852e-01],
       [ 2.288e+00],
       [-1.186e+00],
       [-9.982e-01],
       [-6.852e-01],
       [ 1.285e-01],
       [-1.280e+00],
       [ 1.412e+00],
       [-3.410e-01],
       [-1.249e+00],
       [ 2.319e+00],
       [ 1.036e+00],
       [-1.219e-01],
       [-1.155e+00],
       [-3.784e+00],
       [-8.417e-01],
       [-7.791e-01],
       [-1.436e+00],
       [ 1.850e+00],
       [ 2.850e-01],
       [-1.155e+00],
       [-2.800e-02],
       [-1.155e+00],
       [ 5.666e-01],
       [-9.356e-01],
       [-9.356e-01],
       [-6.852e-01],
       [ 1.318e+00],
       [ 7.544e-01],
       [ 1.285e-01],
       [-1.405e+00],
       [ 2.537e-01],
       [-1.655e+00],
       [ 9.719e-02],
       [-2.158e-01],
       [ 2.850e-01],
       [ 1.285e-01],
       [-1.061e+00],
       [-7.478e-01],
       [-1.532e-01],
       [-1.219e-01],
       [-3.097e-01],
       [ 3.460e-02],
       [-4.349e-01],
       [-1.092e+00],
       [-9.356e-01],
       [-1.374e+00],
       [ 3.476e-01],
       [-4.975e-01],
       [-2.000e+00],
       [ 1.911e-01],
       [ 2.537e-01],
       [-6.539e-01],
       [ 2.224e-01],
       [-9.669e-01],
       [-1.155e+00],
       [-1.030e+00],
       [ 2.038e+00],
       [ 2.069e+00],
       [ 3.163e-01],
       [ 1.349e+00],
       [ 2.132e+00],
       [-1.532e-01],
       [-1.155e+00],
       [-2.158e-01],
       [-1.030e+00],
       [-1.155e+00],
       [ 9.719e-02],
       [-7.478e-01],
       [-3.410e-01],
       [-5.600e-01],
       [-1.123e+00],
       [ 1.285e-01],
       [ 2.413e+00],
       [-1.061e+00],
       [-6.852e-01],
       [-9.356e-01],
       [-8.104e-01],
       [-6.852e-01],
       [-9.043e-01],
       [ 1.036e+00],
       [ 3.301e-03],
       [-1.342e+00],
       [ 2.850e-01],
       [-3.097e-01],
       [-7.165e-01],
       [ 6.918e-01],
       [-5.929e-02],
       [-4.036e-01],
       [-9.059e-02],
       [ 3.789e-01],
       [ 2.382e+00],
       [ 9.422e-01],
       [-3.723e-01],
       [ 3.301e-03],
       [-6.539e-01],
       [ 9.719e-02],
       [-8.730e-01],
       [ 6.918e-01],
       [-5.600e-01],
       [ 1.725e+00],
       [-1.499e+00],
       [-3.097e-01],
       [-2.784e-01],
       [ 3.476e-01],
       [-1.217e+00],
       [ 6.590e-02],
       [ 2.100e+00],
       [-1.687e+00],
       [-9.982e-01],
       [ 1.631e+00],
       [-3.723e-01],
       [-4.036e-01],
       [-7.791e-01],
       [ 9.719e-02],
       [ 9.109e-01],
       [ 1.944e+00],
       [ 9.719e-02],
       [ 1.881e+00],
       [-9.043e-01],
       [ 9.735e-01],
       [-3.097e-01],
       [-4.662e-01],
       [ 1.662e+00],
       [ 1.474e+00],
       [-4.975e-01],
       [ 5.354e-01],
       [-4.662e-01],
       [-1.219e-01],
       [-1.655e+00],
       [-2.784e-01],
       [-5.929e-02],
       [-2.784e-01],
       [-9.043e-01],
       [ 1.944e+00],
       [-8.417e-01],
       [-4.036e-01],
       [-9.669e-01],
       [ 1.285e-01],
       [ 3.476e-01],
       [ 2.224e-01],
       [-8.417e-01],
       [-2.158e-01],
       [-5.913e-01],
       [-3.097e-01],
       [ 2.224e-01],
       [-9.043e-01],
       [-5.288e-01],
       [-5.288e-01],
       [-8.417e-01],
       [-7.478e-01],
       [-6.539e-01],
       [-5.913e-01],
       [ 2.224e-01],
       [ 8.170e-01],
       [-9.669e-01],
       [-5.600e-01],
       [ 1.130e+00],
       [ 1.443e+00],
       [ 1.819e+00],
       [ 4.728e-01],
       [-4.349e-01],
       [-9.356e-01],
       [-1.219e-01],
       [ 6.590e-02],
       [-2.800e-02],
       [-4.662e-01],
       [ 1.067e+00],
       [-6.226e-01],
       [-2.800e-02],
       [ 1.911e-01],
       [-1.280e+00],
       [ 1.286e+00],
       [ 2.444e+00],
       [ 1.443e+00],
       [ 7.544e-01],
       [-1.845e-01],
       [-2.784e-01],
       [ 7.544e-01],
       [-3.097e-01],
       [-7.165e-01],
       [ 1.036e+00],
       [ 1.380e+00],
       [-6.852e-01],
       [-1.655e+00],
       [ 6.590e-02],
       [-9.356e-01],
       [ 2.319e+00],
       [ 1.099e+00],
       [-8.730e-01],
       [ 3.301e-03],
       [-6.226e-01],
       [-2.031e+00],
       [ 1.286e+00],
       [-8.104e-01],
       [ 1.285e-01],
       [ 4.728e-01],
       [ 2.537e-01],
       [ 2.850e-01],
       [-4.349e-01],
       [ 5.979e-01],
       [ 7.231e-01],
       [-4.349e-01],
       [ 1.161e+00],
       [ 3.301e-03],
       [ 2.537e-01],
       [-9.669e-01],
       [ 6.605e-01],
       [ 1.506e+00],
       [-6.852e-01],
       [ 1.911e-01],
       [-9.059e-02],
       [ 3.460e-02],
       [ 1.285e-01],
       [ 1.474e+00],
       [ 2.537e-01],
       [-3.410e-01],
       [-1.280e+00],
       [-1.845e-01],
       [ 1.911e-01],
       [ 1.349e+00],
       [-8.730e-01],
       [ 1.161e+00],
       [ 1.598e-01],
       [ 2.537e-01],
       [ 4.102e-01],
       [-5.913e-01],
       [ 2.069e+00],
       [ 1.631e+00],
       [-8.417e-01],
       [-4.036e-01],
       [-7.478e-01],
       [-1.186e+00],
       [-2.158e-01],
       [ 8.796e-01],
       [-1.219e-01],
       [-3.097e-01],
       [-2.784e-01],
       [-1.532e-01],
       [ 6.292e-01],
       [ 1.693e+00],
       [-9.043e-01],
       [ 2.850e-01],
       [-2.800e-02],
       [ 1.662e+00],
       [-4.662e-01],
       [-4.975e-01],
       [-8.104e-01],
       [ 1.598e-01],
       [-1.749e+00],
       [-6.852e-01],
       [-5.913e-01],
       [-2.800e-02],
       [-5.913e-01],
       [-3.723e-01],
       [ 5.979e-01],
       [ 1.005e+00],
       [-6.539e-01],
       [ 8.170e-01],
       [-1.249e+00],
       [ 2.069e+00],
       [ 1.286e+00],
       [ 4.728e-01],
       [ 3.301e-03],
       [-4.036e-01],
       [ 1.881e+00],
       [ 1.036e+00],
       [ 2.224e-01],
       [ 5.041e-01],
       [ 6.590e-02],
       [-4.662e-01],
       [ 2.163e+00],
       [-1.030e+00],
       [ 1.537e+00],
       [-9.982e-01],
       [-6.226e-01],
       [ 3.460e-02],
       [ 3.301e-03],
       [ 1.598e-01],
       [-8.730e-01]])

In [13]:
# b) Create a new X with all the attributes of the all X but the standarized glucose.

array = p_indians.values
bef_gluc = array[:,0:1]
aft_gluc = array[:,2:8]
X = np.concatenate((bef_gluc, stand_gluc, aft_gluc), axis = 1)
X

array([[ 6.000e+00,  8.483e-01,  7.200e+01, ...,  3.360e+01,  6.270e-01,
         5.000e+01],
       [ 1.000e+00, -1.123e+00,  6.600e+01, ...,  2.660e+01,  3.510e-01,
         3.100e+01],
       [ 8.000e+00,  1.944e+00,  6.400e+01, ...,  2.330e+01,  6.720e-01,
         3.200e+01],
       ...,
       [ 5.000e+00,  3.301e-03,  7.200e+01, ...,  2.620e+01,  2.450e-01,
         3.000e+01],
       [ 1.000e+00,  1.598e-01,  6.000e+01, ...,  3.010e+01,  3.490e-01,
         4.700e+01],
       [ 1.000e+00, -8.730e-01,  7.000e+01, ...,  3.040e+01,  3.150e-01,
         2.300e+01]])

In [14]:
# c) Do the same Scaling (from 0 to 1) instead of Standarizing. 

res_gluc = MinMaxScaler(feature_range=(0,1)).fit_transform(gluc)
X = np.concatenate((bef_gluc, res_gluc, aft_gluc), axis = 1)
X

array([[ 6.   ,  0.744, 72.   , ..., 33.6  ,  0.627, 50.   ],
       [ 1.   ,  0.427, 66.   , ..., 26.6  ,  0.351, 31.   ],
       [ 8.   ,  0.92 , 64.   , ..., 23.3  ,  0.672, 32.   ],
       ...,
       [ 5.   ,  0.608, 72.   , ..., 26.2  ,  0.245, 30.   ],
       [ 1.   ,  0.633, 60.   , ..., 30.1  ,  0.349, 47.   ],
       [ 1.   ,  0.467, 70.   , ..., 30.4  ,  0.315, 23.   ]])

<h1>Normalize Data </h1>

Normalization works with observations (rows) instead of attributes (columns). 

The idea here is to have a length 1 for each observation (a vector of length 1 in linear algebra).

It is useful in algorithms that weigth input values as a whole, such is the case of Neural Networks
and also distance algorithms such as K-nn (Nearest Neighbors)

For normalization you use the <b>Normalizer</b> class.

In [15]:
from sklearn.preprocessing import Normalizer

p_indians.head()

scaler = Normalizer().fit(X)
normalizedX = scaler.transform(X)

normalizedX

   pregnancies  glucose  pressure  skin  insulin   bmi   pedi  age  outcome
0            6      148        72    35        0  33.6  0.627   50        1
1            1       85        66    29        0  26.6  0.351   31        0
2            8      183        64     0        0  23.3  0.672   32        1
3            1       89        66    23       94  28.1  0.167   21        0
4            0      137        40    35      168  43.1  2.288   33        1

array([[0.06 , 0.007, 0.717, ..., 0.335, 0.006, 0.498],
       [0.012, 0.005, 0.796, ..., 0.321, 0.004, 0.374],
       [0.106, 0.012, 0.846, ..., 0.308, 0.009, 0.423],
       ...,
       [0.035, 0.004, 0.511, ..., 0.186, 0.002, 0.213],
       [0.012, 0.008, 0.732, ..., 0.367, 0.004, 0.573],
       [0.012, 0.005, 0.818, ..., 0.355, 0.004, 0.269]])

<h1>Binarize Data </h1>

Binarize consist in transforming data using a binary threshold; all values above are marked as 1
and all values below as zero. 

Sometimes you want to transform probabilities into crisp values. Many times it is used in feature engineering
when you add a new feature. 

For binarization you use the <b>Binarizer</b> class.

In [16]:
from sklearn.preprocessing import Binarizer

p_indians.head()

binarizer=Binarizer(threshold=0.0).fit(X)
binaryX=binarizer.transform(X)

binaryX[:10,0:8]

   pregnancies  glucose  pressure  skin  insulin   bmi   pedi  age  outcome
0            6      148        72    35        0  33.6  0.627   50        1
1            1       85        66    29        0  26.6  0.351   31        0
2            8      183        64     0        0  23.3  0.672   32        1
3            1       89        66    23       94  28.1  0.167   21        0
4            0      137        40    35      168  43.1  2.288   33        1

array([[1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0., 0., 1., 1.]])

<h1>Three useful functions: map, zip and filter </h1>

There are three very useful functions many times used in preprocessing for econdinf, filter or interation. 

They are: map, zip and filter.

<h1>map</h1> 

Let's you apply a function to a sequence of elements like a list or a dictionnary.

Very useful for encoding. Please remember that it results an iterator that must be converted to a list to be used.

In [17]:
#map 

ln=["1","2","3","4","5"]
dn={"1":"10","2":"20","3":"30","4":"40","5":"50"}

list(map(lambda x: int(x),ln))

list(map(lambda x:int(x),dn))

[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

<b><font color="red" size=6>Mission 2</font>

a) We want to highlight everybody with a glucose level over 140 setting it to 1. 
<br><br>
b) We'll do the same with blood pressure over 80. 
<br><br>
c) Finally we will create a new attribute that we will name warning, when both 
glucose and blood pressure is set to 1, being 0 otherwise. 
<br><br>
d) We need a new X (let's call it X_new) with these attributes instead of the original ones.

</b>

In [18]:
# a) We want to highlight everybody with a glucose level over 140 setting it to 1. 

glucose_array = p_indians[["glucose"]]
p_indians["gluc_over_140"] = Binarizer(threshold = 140.0).fit(glucose_array).transform(glucose_array)
p_indians

,pregnancies,glucose,pressure,skin,insulin,bmi,pedi,age,outcome,gluc_over_140
0,6,148,72,35,0,33.6,0.627,50,1,1
1,1,85,66,29,0,26.6,0.351,31,0,0
2,8,183,64,0,0,23.3,0.672,32,1,1
3,1,89,66,23,94,28.1,0.167,21,0,0
4,0,137,40,35,168,43.1,2.288,33,1,0
...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0,0
764,2,122,70,27,0,36.8,0.340,27,0,0
765,5,121,72,23,112,26.2,0.245,30,0,0
766,1,126,60,0,0,30.1,0.349,47,1,0
767,1,93,70,31,0,30.4,0.315,23,0,0

In [19]:
# b) We'll do the same with blood pressure over 80. 

pressure_array = p_indians[["pressure"]]
p_indians["pressure_over_80"] = Binarizer(threshold = 80.0).fit(pressure_array).transform(pressure_array)
p_indians

,pregnancies,glucose,pressure,skin,insulin,bmi,pedi,age,outcome,gluc_over_140,pressure_over_80
0,6,148,72,35,0,33.6,0.627,50,1,1,0
1,1,85,66,29,0,26.6,0.351,31,0,0,0
2,8,183,64,0,0,23.3,0.672,32,1,1,0
3,1,89,66,23,94,28.1,0.167,21,0,0,0
4,0,137,40,35,168,43.1,2.288,33,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0,0,0
764,2,122,70,27,0,36.8,0.340,27,0,0,0
765,5,121,72,23,112,26.2,0.245,30,0,0,0
766,1,126,60,0,0,30.1,0.349,47,1,0,0
767,1,93,70,31,0,30.4,0.315,23,0,0,0

In [23]:
# c) Finally we will create a new attribute that we will name warning, when both 
# glucose and blood pressure is set to 1, being 0 otherwise. 

name_warning_list = []
n = len(p_indians)

for x in range(n):
    if (p_indians["gluc_over_140"].iloc[x] == 1 & p_indians["pressure_over_80"].iloc[x] == 1):
        name_warning_list.append(1)
    else:
        name_warning_list.append(0)
        
name_warning_array = np.asarray(name_warning_list)

p_indians["name_warning"] = name_warning_array
p_indians

,pregnancies,glucose,pressure,skin,insulin,bmi,pedi,age,outcome,gluc_over_140,pressure_over_80,name_warning
0,6,148,72,35,0,33.6,0.627,50,1,1,0,0
1,1,85,66,29,0,26.6,0.351,31,0,0,0,0
2,8,183,64,0,0,23.3,0.672,32,1,1,0,0
3,1,89,66,23,94,28.1,0.167,21,0,0,0,0
4,0,137,40,35,168,43.1,2.288,33,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0,0,0,0
764,2,122,70,27,0,36.8,0.340,27,0,0,0,0
765,5,121,72,23,112,26.2,0.245,30,0,0,0,0
766,1,126,60,0,0,30.1,0.349,47,1,0,0,0
767,1,93,70,31,0,30.4,0.315,23,0,0,0,0

In [24]:
# d) We need a new X (let's call it X_new) with these attributes instead of the original ones.

array = p_indians.values
X_new = array[:,0:12]
X_new

array([[  6., 148.,  72., ...,   1.,   0.,   0.],
       [  1.,  85.,  66., ...,   0.,   0.,   0.],
       [  8., 183.,  64., ...,   1.,   0.,   0.],
       ...,
       [  5., 121.,  72., ...,   0.,   0.,   0.],
       [  1., 126.,  60., ...,   0.,   0.,   0.],
       [  1.,  93.,  70., ...,   0.,   0.,   0.]])

<h1>zip</h1> 

It enables you to iterate over two or more lists at the same time.

In [25]:
#zip

first = [1, 3, 8, 4, 9]
second = [2, 2, 7, 5, 8]

# Iterate over two or more list at the same time
for x, y in zip(first, second):
    print(x + y)

3
5
15
9
17

<h1>filter</h1> 

Similar to map() but in this case will return True or False.

In [26]:
#filter

ln=["1","2","3","4","5"]
dn={"1":"10","2":"20","3":"30","4":"40","5":"50"}

list(filter(lambda x:int(x)>1,ln))

list(filter(lambda x:int(x)>1,dn))
list(filter(lambda x:int(x)>10,dn.values()))

['2', '3', '4', '5']

['2', '3', '4', '5']

['20', '30', '40', '50']

In [27]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Will return true if input number is even
def even(x):
    return x % 2 == 0
 
even_n = filter(even, numbers)
even_n1 = filter(lambda x: x % 2==0, numbers)

list(even_n)
list(even_n1)

[2, 4, 6, 8, 10]

[2, 4, 6, 8, 10]